tasks:
  - init: |
      sudo apt update
      sudo apt install -y mysql-server
      pip install flask mysql-connector-python werkzeug
      sudo service mysql start
      mysql -u root -e "CREATE DATABASE IF NOT EXISTS user_management;"
      mysql -u root user_management < database_setup.sql
  - command: python app.py

ports:
  - port: 8080
    onOpen: open-preview
